typography_spectrum: 0.42514804448001087
color:
  saturation: 0.05797981424257159
  brandStrength: 0.5016759049613029
  rhythmicContrast: 0.1943431799300015
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  lightness: 0.10460612643510103
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8018604309763759
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Juan Paolo Sandig
  email: siathry@yahoo.com
  url: ''
name: Siathry
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Siathry
description: 'travel, art, love and adventure'
purpose: []
